<?php

/**
 * @file
 * Contains my_users.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;
use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_theme_suggestions_HOOK() for contact form suggestion.
 */
function my_users_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
    $original_theme_hook = $variables['theme_hook_original'];

    $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
  }

  return $suggestions;
}

/**
 * Implements hook_theme().
 */
function my_users_theme() {
  return [
    'register_users_block' => [
      'variables' => [
        'form_register_users' => NULL,
        'form_register_users_modal' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}


function my_users_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['#submit'][] = '_my_users_set_log';

}

function _my_users_set_log(&$form, FormStateInterface $form_state) {

  $request = Request::createFromGlobals();
  $uid = \Drupal::currentUser()->id();
  $ip = $request->getClientIp();
  $type = 'LOGIN';
  $date =  \Drupal::time()->getCurrentTime();

  \Drupal::logger('my_users')->info("Campos Login: @uid, @ip, @type, @date", ['@uid' => $uid, '@ip' => $ip, '@type' =>$type, '@date' => $date]);

  \Drupal::database()
    ->insert('logs_login_register')
    ->fields([
      'uid' => $uid,
      'ip' => $ip,
      'type' => $type,
      'date_timestamp' => $date
    ])
    ->execute();
}

/**
 * Implements hook_user_insert().
 *
 */
function my_users_user_insert(Drupal\Core\Entity\EntityInterface $entity) {

  $messenger = \Drupal::messenger();
  $messenger->addMessage(t('Registro intervenido'), 'status');

  $request = Request::createFromGlobals();
  $uid = \Drupal::currentUser()->id();
  $ip = $request->getClientIp();
  $type = 'REGISTER';
  $date =  \Drupal::time()->getCurrentTime();

  \Drupal::logger('my_users')->notice("Campos Register: @uid, @ip, @type, @date", ['@uid' => $uid, '@ip' => $ip, '@type' =>$type, '@date' => $date]);

  \Drupal::database()
    ->insert('logs_login_register')
    ->fields([
      'uid' => $uid,
      'ip' => $ip,
      'type' => $type,
      'date_timestamp' => $date
    ])
    ->execute();
}
