<?php

/**
 * @file
 * Contains my_users.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme_suggestions_HOOK() for contact form suggestion.
 */
function my_users_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
    $original_theme_hook = $variables['theme_hook_original'];

    $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
  }

  return $suggestions;
}


/**
 * Implements hook_help().
 */
function my_users_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_users module.
    case 'help.page.my_users':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module Test for Serempre') . '</p>';
      return $output;

    default:
  }
}



/**
 * Implements hook_theme().
 */
function my_users_theme() {
  return [
    'register_users_block' => [
      'variables' => [
        'form_register_users' => NULL,
        'form_register_users_modal' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
